version: '3'

services:
  app:
    image: groceries:latest
    command: :8080 redis:6379 /users.json
    volumes:
      - "./users.json:/users.json"
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
