# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/groceries .
  run:
    cmds:
      - ./groceries
    deps: [build]
    sources:
      - static/*
      - *.go
      - index.html
